AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-rss

  SAM Template for lambda-rss

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  RSSFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: rss/
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          DYNAMODB_TABLE: ""
          TELEGRAM_TOKEN: ""
          TELEGRAM_CHAT_ID: ""
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
      Events:
        RSS:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Name: schedule
            Description: Run every hour
            Enabled: True

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RSSFunction:
    Description: "RSS Lambda Function ARN"
    Value: !GetAtt RSSFunction.Arn
  RSSFunctionIamRole:
    Description: "Implicit IAM Role created for RSS function"
    Value: !GetAtt RSSFunctionRole.Arn
